version: 1.0.{build}
branches:
  only:
    - master
os:
  - Visual Studio 2015
clone_depth: 1
configuration:
  - Debug
platform:
  - x64
environment:
  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.64.0
    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly

build_script: mk/appveyor.bat
